import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderAsoinco from "../app/layouts/HeaderAsoinco";
import FooterAsoinco from "./layouts/FooterAsoinco";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">

      <body className={inter.className}>
        <HeaderAsoinco></HeaderAsoinco>
        {children}
        <FooterAsoinco></FooterAsoinco>
      </body>

    </html>
  );
}
